---
title: "Multi-site simulations"
author: ''
date: "11/8/2017"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("/users/eric.ward/downloads/linear_chain_staticB_multisite.3.Blow.OElow.Rdata")
```

## Convergence statistics

This indicates that about 35% of the time the model is converging
```{r}
z = unlist(lapply(saved_output, getElement, 'converged'))
print(table(z))
```

## Errors

A basic thing seems like the model is having a hard time accurately classifying observation versus process error. These are all low - observation error scenarios (sd = 0.01) with process variance being higher (sd = 0.02). 

```{r}
pro = 0
idx = which(saved_output[[1]]$estimate$term == "resid_process_sd[1]")
for(i in 1:length(saved_output)) {
  pro[i] = saved_output[[i]]$estimate$estimate[idx]
}

obs = 0
idx = which(saved_output[[1]]$estimate$term == "obs_sd[1]")
for(i in 1:length(saved_output)) {
  obs[i] = saved_output[[i]]$estimate$estimate[idx]
}

par(mfrow = c(2,2), mgp = c(2,1,0))
hist(obs, 40, col="grey", xlab="Observation error sd")
hist(pro, 40, col="grey", xlab="Process error sd")
plot(obs, pro, xlab="Observation error sd", ylab="Process error sd")
```

# B matrix

```{r}
par(mfrow = c(4,4), mai=c(0.4,0.4,0.1,0.1), mgp = c(2,1,0))

for(i in 1:4) {
  for(j in 1:4) {
    # loop through all simulations
    idx = which(saved_output[[1]]$estimate$term == paste0("B[1,",i,",",j,"]"))
    obs = NA
    pred = NA
    for(k in 1:length(saved_output)) {
      pred = c(pred, saved_output[[k]]$estimate$estimate[idx])
      obs = c(obs, saved_output[[k]]$sim_output$B_mat[i,j,1])
    }
    plot(obs, pred, xlab="Obs", ylab ="Pred")
    abline(0,1, col="red")
  }
}
```




